# Form implementation generated from reading ui file 'lab1ui.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.voteAlice = QtWidgets.QPushButton(parent=self.centralwidget)
        self.voteAlice.setGeometry(QtCore.QRect(50, 110, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.voteAlice.setFont(font)
        self.voteAlice.setObjectName("voteAlice")
        self.voteBob = QtWidgets.QPushButton(parent=self.centralwidget)
        self.voteBob.setGeometry(QtCore.QRect(200, 110, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.voteBob.setFont(font)
        self.voteBob.setObjectName("voteBob")
        self.voteCharlie = QtWidgets.QPushButton(parent=self.centralwidget)
        self.voteCharlie.setGeometry(QtCore.QRect(350, 110, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.voteCharlie.setFont(font)
        self.voteCharlie.setObjectName("voteCharlie")
        self.voteDerek = QtWidgets.QPushButton(parent=self.centralwidget)
        self.voteDerek.setGeometry(QtCore.QRect(500, 110, 100, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.voteDerek.setFont(font)
        self.voteDerek.setObjectName("voteDerek")
        self.resultsButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.resultsButton.setGeometry(QtCore.QRect(100, 200, 150, 100))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.resultsButton.setFont(font)
        self.resultsButton.setObjectName("resultsButton")
        self.saveButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(400, 200, 150, 100))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.saveButton.setFont(font)
        self.saveButton.setObjectName("saveButton")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(200, 330, 256, 151))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 650, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.voteAlice.setText(_translate("MainWindow", "Alice"))
        self.voteBob.setText(_translate("MainWindow", "Bob"))
        self.voteCharlie.setText(_translate("MainWindow", "Charlie"))
        self.voteDerek.setText(_translate("MainWindow", "Derek"))
        self.resultsButton.setText(_translate("MainWindow", "Results"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:6.6pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Alice:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Bob:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Charlie:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Derek:</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
